#!/usr/bin/env python
import numpy as np

class DataLoader(object):
  """
  This class abstract the process of loading data from a variety of formats,
  including CSVs and NPZ, generated by different data sources.
  """
  _datafilepath = None

  # data matrix
  matrix = None

  # string identifying the source of the data
  source = None

  # object representing the source data, if any
  source_obj = None

  # metadata etc as a string, which is sometimes a JSON
  # string
  header = ''

  def __init__(self, datafilepath, file_content=None):
    """
    Creates a data loader for the given file. The resulting object
    will expose:
      - matrix: numpy array
      - source: string identifying source of the data, determined from content
                and extension of datafilepath
      - header: data metadata as a string, which maybe a JSON string.
      - source_obj: an object representing the data, which may provide
                   additional information. This may be None

    datafilepath: path to the datafile
    file_content: content of the file. If given no attempt will be made to load
                 the file from disk
    """

    self._datafilepath = datafilepath

    matrix = None
    source = None
    source_obj = None
    header = ''

    if file_content:
      toload = file_content
    else:
      toload = datafilepath

    if datafilepath.endswith('csv'):
      import csvtools
      csv = csvtools.CSVReader(toload)
      matrix = csv.mat
      source = csv.csv_source
      header = csv.header

    if datafilepath.endswith('trc'):
      from lecroy import LecroyBinaryWaveform
      bwave = LecroyBinaryWaveform(datafilepath, file_content)
      matrix = bwave.mat
      source = 'LECROYWR104Xi_binary'
      source_obj = bwave

    if datafilepath.endswith('.npz'):
      npzfile = np.load(toload)
      if 'source' in npzfile:
        source = npzfile['source'].item()
      else:
        source = None

      if datafilepath.endswith('.power.npz'):
        matrix = npzfile['data']
        header = npzfile['header'].item()
        if source is None:
          source = 'calc_power_spectrum.py'

      if source == 'wzextract.py':
        matrix = npzfile['data']
        header = npzfile['header'].item()

      if source == 'average_traces.py':
        matrix = npzfile['data']
        header = npzfile['header'].item()

      if type(header) is dict:
        import json
        header = json.dumps(header, indent=1, sort_keys=True)

    assert matrix is not None
    assert type(header) == str

    self.matrix = matrix
    self.header = header
    self.source = source
    self.source_obj = source_obj

  @property
  def xy_labels(self):
    source = self.source
    ret = 'X LABEL', 'Y LABEL'
    if source is not None:
      if source == 'SIOS':
        ret = 'Z Position (mm)', 'Fluoresence (V)'

      if source.startswith('LECROY'):
        ret = 'Time (seconds)', 'Y LABEL (V)'

      if source == 'calc_power_spectrum.py':
        ret = 'Frequency (KHz)', '$V^{\ 2}$'

      if source == 'wzextract.py':
        ret = 'Z position (um)', 'PMT Voltage (V)'

    return ret
